In [0]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
np.random.seed(0)

In [0]:
iris=load_iris()
df=pd.DataFrame(data=iris.data, columns= iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [0]:
df['species']=pd.Categorical.from_codes(iris.target, iris.target_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [0]:
df['is_train']=np.random.uniform(0,1, len(df)) <=.75

In [0]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  is_train  
0  setosa      True  
1  setosa      True  
2  setosa      True  
3  setosa      True  
4  setosa      True

In [0]:
train, test= df[df['is_train']==True], df[df['is_train']==False]

In [0]:
test


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
7                  5.0               3.4                1.5               0.2   
8                  4.4               2.9                1.4               0.2   
10                 5.4               3.7                1.5               0.2   
13                 4.3               3.0                1.1               0.1   
17                 5.1               3.5                1.4               0.3   
18                 5.7               3.8                1.7               0.3   
19                 5.1               3.8                1.5               0.3   
20                 5.4               3.4                1.7               0.2   
21                 5.1               3.7                1.5               0.4   
23                 5.1               3.3                1.7               0.5   
27                 5.2               3.5                1.5               0.2   
31                 5.4               3.4                1.5               0.4   
38                 4.4               3.0                1.3               0.2   
52                 6.9               3.1                4.9               1.5   
66                 5.6               3.0                4.5               1.5   
68                 6.2               2.2                4.5               1.5   
70                 5.9               3.2                4.8               1.8   
72                 6.3               2.5                4.9               1.5   
89                 5.5               2.5                4.0               1.3   
98                 5.1               2.5                3.0               1.1   
103                6.3               2.9                5.6               1.8   
109                7.2               3.6                6.1               2.5   
111                6.4               2.7                5.3               1.9   
114                5.8               2.8                5.1               2.4   
116                6.5               3.0                5.5               1.8   
118                7.7               2.6                6.9               2.3   
122                7.7               2.8                6.7               2.0   
140                6.7               3.1                5.6               2.4   
143                6.8               3.2                5.9               2.3   
144                6.7               3.3                5.7               2.5   
147                6.5               3.0                5.2               2.0   
149                5.9               3.0                5.1               1.8   

        species  is_train  
7        setosa     False  
8        setosa     False  
10       setosa     False  
13       setosa     False  
17       setosa     False  
18       setosa     False  
19       setosa     False  
20       setosa     False  
21       setosa     False  
23       setosa     False  
27       setosa     False  
31       setosa     False  
38       setosa     False  
52   versicolor     False  
66   versicolor     False  
68   versicolor     False  
70   versicolor     False  
72   versicolor     False  
89   versicolor     False  
98   versicolor     False  
103   virginica     False  
109   virginica     False  
111   virginica     False  
114   virginica     False  
116   virginica     False  
118   virginica     False  
122   virginica     False  
140   virginica     False  
143   virginica     False  
144   virginica     False  
147   virginica     False  
149   virginica     False

In [0]:
y=pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
features=df.columns[:4]
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [0]:
clf=RandomForestClassifier(n_jobs=2, random_state=0)
clf.fit(train[features], y)

/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [0]:
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
clf.predict_proba(test[features])[10:20]

array([[1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [1. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0. , 1. , 0. ],
       [0. , 0.9, 0.1],
       [0. , 0.2, 0.8],
       [0. , 0.3, 0.7],
       [0. , 1. , 0. ],
       [0. , 0.8, 0.2]])

In [0]:
preds=iris.target_names[clf.predict(test[features])]

In [0]:
preds

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'versicolor', 'versicolor', 'versicolor', 'virginica',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'virginica', 'virginica', 'virginica'],
      dtype='<U10')